#cloud-config
package_update: true
package_upgrade: true
users:
  - name: ryan
    groups: [ sudo ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4lY4YcpVi2KaH2xMzXCRbJ0S/PztQMlUHoCKTIjWEybREpfntD0hhaaKIUw8UUR4324mA5JVpBzlGyMusKFlVmbaMjkfNZpUyqR4OW4zcTEXXnowbD6FZpfMejPJl9WLD5Pmt88TM4NfqOhsqmInXj3X6iBpBdZ94bWLfFrNOYNqCInL3t91Ks3DHbD8MbwMJ4itPb6m3RAEkvVc1ImEo9NVpMKuSbyjbiQTuDHsLajCGOI6tf4IgZw2MIq9QnfklhxHfswTfjpN3hVhJgAtSwjbicXzn0gKGoxQvqK0mLtzMMe0/12pspT7b7Pwg6Boygat1PS1CryHJmCfdy0xf ryan@Ryans-MacBook-Pro.local'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNNgeVYR+Zfl32Zhv/sJfpMXNlIuK0h+VGkGUBDZJqAqQ9cMxFzV9Xb7T2UgS0QEMre/5aiMUhPvFBDdUw+7ErlV9rZ8N2kruIBDt3eIBPGDuDuX+fQ3lkjKnJ19P/F4v9wwvcVnrOL+7XdZQMKSI+QTtnCLWhRwNu0mMX+0La+5q/azTRcydVVJPZH+f3o+Eu0MdJtsWEbp5XOVSYTODKeX5ozJYCX1vHqBBlNu11isY8pfEUB4BXV27dQPCeVLw9qE3xCA8o2KloI3rrylzlP3ZbCDIu3+cLPzggMKpvuom4mkSRQqZ1Q0oNKKBomf9d20CGmHso3yc9d2jVvOwVuirHMjgAxvVuoEWgUNrOSiBK8UkPTfNKsh7GGhjpZWFwI7ogaqEZLyKggErbF9eWGlzMYFZE8XuFquRUL7PvsveJxE3xODbRxAo+n9DPjaOhVANkkt52oL69CG0fTU+HI4Fb3FplvTLd1LWTjQ3wLyL0a40Vz4+R8chu5fVP9CXaM6lTEeHTy78lZp8YBhJw9/8rB+wBzRPX0koyDPs9x/1AgMf+2y9JAXewdUTWdWzJQo2HV6+lHDyL/3r9UteeqqmEvQimuz7BqR1ifhaptj+VOui29Ukf/HZAAwGP9Y7fNs64DkrKtCHyttzKj6+LXaEVLsBJbILkc/HANq8uHw== ryan@hyperion'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGps4bNYLE9NitCKsZuSEk7OUli7EBs/BvTHXgAKN6Ec9/BqVHBcbvhBRmGaRi5cvVYu5qo4zSegMlcAfqZ2mijI3vm9GQi+0RkvvIMWO5j2MmRaaTjjOAZRSvPvKNhOJ1O47OCYSr1hozW+7l4zVPUPw4rqugQETBb2nU2CXnY2naCll+T/JE+vkAswICSZl1PJwkUyxyGRIsey1m3VPSlYHVAhKAYDXpWgvI7QHE7m+dydroZNzgdBdQ93KgL3k/wU7OwJVy4WR1lOTcg4yN3Lsb1zUsUg8EgAwaW9ytl9OlVdId04yM1t4iTaBQ63aO/OKD+2fQWILPtJjasWap ryan@tycho.local'
packages:
    - python
    - python-apt
    - python3-apt
    - build-essential
    - unzip
    - jq
    - git
snap:
    commands:
      00: snap install yq
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}